# Site settings
title: Santiago de Diego
description: My personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Santiago de Diego
user_description: Interested in everything related to science and technology, specially in security. Amateur rugby and tennis player.
user_title: Mathematician and IT engineer
email: santidediego@gmail.com
twitter_username: santidediego
github_username:  santidediego

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
