# Site settings
title: Santiago de Diego
description: My personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Santiago de Diego
user_description: Double Degree in maths and Computer Science by the University of Granada (UGR), Master´s Degree in Information Security by the International University of La Rioja (UNIR), CPHE Certified, and PhD Student by the University of Granada. Santiago works as a Cybersecurity and Distributed Ledger Technologies Researcher at Tecnalia Research & Innovation in Bilbao, Spain.
user_title: Cybersecurity and DLTs Researcher
email: santidediego@gmail.com
twitter_username: santidediego
github_username:  santidediego

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
